baseURL = "http://diagnosis.letb.cl"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "meghna-hugo"

[context.production.environment]
    HUGO_VERSION = "0.55.6"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"



[context.deploy-preview.environment]
    HUGO_VERSION = "0.53"

[context.split1]
    command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
    HUGO_VERSION = "0.55.6"
    HUGO_ENV = "production"

[context.deploy-preview]
    command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
    command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
    HUGO_VERSION = "0.55.6"

[context.next.environment]
    HUGO_ENABLEGITINFO = "true"


[build]
publish = "public"
command = "hugo --gc --minify"